language: node_js
notifications:
  email: false
node_js:
  - node
cache:
directories:
- node_modules
services:
  - xvfb
before_script:
  - npm prune
  - "export DISPLAY=:99.0"
before_install:
  - google-chrome-stable --headless --disable-gpu
addons:
  chrome: stable
