language: node_js
notifications:
  email: false
node_js:
  - "8"
cache:
directories:
- node_modules
before_script:
  - npm prune
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - google-chrome-stable --headless --disable-gpu
addons:
  chrome: stable